name: Build LaTeX document
on:
  push:
    branches: [ main ]
jobs:
  build_resumes:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            dellsperger_cv.tex
            dellsperger_resume.tex
          compiler: pdflatex
      - name: Upload Resume PDF
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: dellsperger*.pdf
  deploy_pages:
    name: "Deploy PDFs"
    needs: build_resumes
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: resume
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy PDFs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main