name: Build LaTeX document
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_resumes:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: |
            dellsperger_resume.tex
            dellsperger_cv.tex
      - name: Upload Resume PDF
        uses: actions/upload-artifact@main
        with:
          name: resume
          path: dellsperger*.pdf
  deploy_pages:
    name: "Deploy PDFs"
    needs: build_resumes
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
        with:
          ref: "gh-pages"
      - name: Setup Pages
        uses: actions/configure-pages@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: resume
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: '.'
      - name: Deploy PDFs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main