name: Build LaTeX document
on:
  push:
    branches: [ main ]
jobs:
  build_resumes:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            dellsperger_cv.tex
            dellsperger_resume.tex
          compiler: pdflatex
      - name: Upload Resume PDF
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: dellsperger_resume.pdf
      - name: Upload Full CV PDF
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: dellsperger_cv.pdf
  deploy_pages:
    name: "Deploy PDFs"
    needs: build_resumes
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: resume
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: resume
      - name: Deploy PDFs
        if: success()
        id: deployment
        uses: actions/deploy-pages@main